// <auto-generated />
using System;
using ERBedSystem.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace ERBedSystem.Migrations
{
    [DbContext(typeof(ErDbContext))]
    [Migration("20260618041253_SeedInitialData")]
    partial class SeedInitialData
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.11");

            modelBuilder.Entity("ERBedSystem.Models.Bed", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Zone")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Beds");

                    b.HasData(
                        new
                        {
                            Id = "ICU-01",
                            Description = "靠近護理站，有生理監視器",
                            Status = "Available",
                            Zone = "ICU"
                        },
                        new
                        {
                            Id = "ICU-02",
                            Description = "葉克膜專用床",
                            Status = "Occupied",
                            Zone = "ICU"
                        },
                        new
                        {
                            Id = "ER-A01",
                            Description = "留觀 A 區靠窗",
                            Status = "Available",
                            Zone = "Ward"
                        },
                        new
                        {
                            Id = "ER-A02",
                            Description = "留觀 A 區，剛出院消毒中",
                            Status = "Cleaning",
                            Zone = "Ward"
                        },
                        new
                        {
                            Id = "PEDS-01",
                            Description = "兒科急診獨立隔離床",
                            Status = "Available",
                            Zone = "Peds"
                        });
                });

            modelBuilder.Entity("ERBedSystem.Models.Encounter", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<string>("BedId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("EndTime")
                        .HasColumnType("TEXT");

                    b.Property<string>("PatientId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("StartTime")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Encounters");
                });

            modelBuilder.Entity("ERBedSystem.Models.Patient", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<string>("ChiefComplaint")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("TriageLevel")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("Patients");

                    b.HasData(
                        new
                        {
                            Id = "P101",
                            ChiefComplaint = "車禍右腳擦傷",
                            Name = "張小明",
                            Status = "Waiting",
                            TriageLevel = 3
                        },
                        new
                        {
                            Id = "P102",
                            ChiefComplaint = "疑似心肌梗塞，OHCA",
                            Name = "王大同",
                            Status = "Waiting",
                            TriageLevel = 1
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
